project_id = "mbjmecduixmsnaxmyaep"

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.buy-points]
verify_jwt = false

[functions.verify-points-payment]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
